version: '3'

services:
  scylla-db:
    image: scylladb/scylla
    hostname: scylla-db
    container_name: scylla-db
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
        rpc-address: 172.18.0.3