/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tsb.ods.stream.schema.avro.kc03;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Schema to replicate transaction kc03 table */
@org.apache.avro.specific.AvroGenerated
public class KC03 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8220604448280103796L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KC03\",\"namespace\":\"com.tsb.ods.stream.schema.avro.kc03\",\"doc\":\"Schema to replicate transaction kc03 table\",\"fields\":[{\"name\":\"trans_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"balance\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<KC03> ENCODER =
      new BinaryMessageEncoder<KC03>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KC03> DECODER =
      new BinaryMessageDecoder<KC03>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<KC03> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<KC03> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<KC03> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<KC03>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this KC03 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a KC03 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a KC03 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static KC03 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String trans_id;
  @Deprecated public java.lang.String name;
  @Deprecated public double balance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KC03() {}

  /**
   * All-args constructor.
   * @param trans_id The new value for trans_id
   * @param name The new value for name
   * @param balance The new value for balance
   */
  public KC03(java.lang.String trans_id, java.lang.String name, java.lang.Double balance) {
    this.trans_id = trans_id;
    this.name = name;
    this.balance = balance;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return trans_id;
    case 1: return name;
    case 2: return balance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: trans_id = (java.lang.String)value$; break;
    case 1: name = (java.lang.String)value$; break;
    case 2: balance = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'trans_id' field.
   * @return The value of the 'trans_id' field.
   */
  public java.lang.String getTransId() {
    return trans_id;
  }


  /**
   * Sets the value of the 'trans_id' field.
   * @param value the value to set.
   */
  public void setTransId(java.lang.String value) {
    this.trans_id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'balance' field.
   * @return The value of the 'balance' field.
   */
  public double getBalance() {
    return balance;
  }


  /**
   * Sets the value of the 'balance' field.
   * @param value the value to set.
   */
  public void setBalance(double value) {
    this.balance = value;
  }

  /**
   * Creates a new KC03 RecordBuilder.
   * @return A new KC03 RecordBuilder
   */
  public static com.tsb.ods.stream.schema.avro.kc03.KC03.Builder newBuilder() {
    return new com.tsb.ods.stream.schema.avro.kc03.KC03.Builder();
  }

  /**
   * Creates a new KC03 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KC03 RecordBuilder
   */
  public static com.tsb.ods.stream.schema.avro.kc03.KC03.Builder newBuilder(com.tsb.ods.stream.schema.avro.kc03.KC03.Builder other) {
    if (other == null) {
      return new com.tsb.ods.stream.schema.avro.kc03.KC03.Builder();
    } else {
      return new com.tsb.ods.stream.schema.avro.kc03.KC03.Builder(other);
    }
  }

  /**
   * Creates a new KC03 RecordBuilder by copying an existing KC03 instance.
   * @param other The existing instance to copy.
   * @return A new KC03 RecordBuilder
   */
  public static com.tsb.ods.stream.schema.avro.kc03.KC03.Builder newBuilder(com.tsb.ods.stream.schema.avro.kc03.KC03 other) {
    if (other == null) {
      return new com.tsb.ods.stream.schema.avro.kc03.KC03.Builder();
    } else {
      return new com.tsb.ods.stream.schema.avro.kc03.KC03.Builder(other);
    }
  }

  /**
   * RecordBuilder for KC03 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KC03>
    implements org.apache.avro.data.RecordBuilder<KC03> {

    private java.lang.String trans_id;
    private java.lang.String name;
    private double balance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tsb.ods.stream.schema.avro.kc03.KC03.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.trans_id)) {
        this.trans_id = data().deepCopy(fields()[0].schema(), other.trans_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.balance)) {
        this.balance = data().deepCopy(fields()[2].schema(), other.balance);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing KC03 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tsb.ods.stream.schema.avro.kc03.KC03 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.trans_id)) {
        this.trans_id = data().deepCopy(fields()[0].schema(), other.trans_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.balance)) {
        this.balance = data().deepCopy(fields()[2].schema(), other.balance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'trans_id' field.
      * @return The value.
      */
    public java.lang.String getTransId() {
      return trans_id;
    }


    /**
      * Sets the value of the 'trans_id' field.
      * @param value The value of 'trans_id'.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder setTransId(java.lang.String value) {
      validate(fields()[0], value);
      this.trans_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'trans_id' field has been set.
      * @return True if the 'trans_id' field has been set, false otherwise.
      */
    public boolean hasTransId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'trans_id' field.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder clearTransId() {
      trans_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'balance' field.
      * @return The value.
      */
    public double getBalance() {
      return balance;
    }


    /**
      * Sets the value of the 'balance' field.
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder setBalance(double value) {
      validate(fields()[2], value);
      this.balance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'balance' field.
      * @return This builder.
      */
    public com.tsb.ods.stream.schema.avro.kc03.KC03.Builder clearBalance() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KC03 build() {
      try {
        KC03 record = new KC03();
        record.trans_id = fieldSetFlags()[0] ? this.trans_id : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.balance = fieldSetFlags()[2] ? this.balance : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KC03>
    WRITER$ = (org.apache.avro.io.DatumWriter<KC03>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KC03>
    READER$ = (org.apache.avro.io.DatumReader<KC03>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.trans_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.trans_id);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    out.writeDouble(this.balance);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.trans_id = null;
      } else {
        this.trans_id = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString();
      }

      this.balance = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.trans_id = null;
          } else {
            this.trans_id = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString();
          }
          break;

        case 2:
          this.balance = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










